import Head from "next/head";
import { useAuth } from "src/lib/auth";
import GitHubIcon from "src/svg/github-icon.svg";

export default function Home() {
  const auth = useAuth();

  const SignInWithGitHub = () => {
    auth?.signInWithGithub();
  };
  const SignOutWithGitHub = () => {
    auth?.signOut();
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex">
        <div className="flex flex-col items-center my-auto w-1/2">
          <img className="h-20" src="/engivia_logo.png" alt="logo" />
          <h1 className="mt-10 text-3xl font-bold text-[#0284C7]">
            エンジビアの泉
          </h1>
          <p className="mb-10 text-[#38BDF8]">
            〜素晴らしきプログラミング豆知識〜
          </p>
          <button
            onClick={SignInWithGitHub}
            className="flex items-center py-2 px-4 hover:bg-gray-100 rounded-md border-2"
          >
            <GitHubIcon />
            <p className="ml-2">Sign in with GitHub</p>
          </button>
          <button
            onClick={SignOutWithGitHub}
            className="py-2 px-4 mt-4 hover:bg-gray-100 rounded-md border-2"
          >
            Sign Out
          </button>
        </div>
        <img
          className="object-cover w-1/2 h-screen"
          src="/AdobeStock_162810993_Preview.jpeg"
          alt="spring"
        />
      </div>
    </div>
  );
}
