#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Styling, testing and building your project before committing"

# Check Prettier standards
yarn check-types ||
(
  echo "🤡😂❌🤡 Failed type check. 🤡😂❌🤡
        Are you seriously trying to write that? Make the changes required above.";
  false;
)

# Check Prettier standards
yarn check-format ||
(
  echo "🤢🤮🤢🤮 ぐごごごご... スタイルやばくね 🤢🤮🤢🤮
        Prettierチェックおかしいよ. yarn formatしてもっかいコミットしてちょ.";
  false;
)

# Check ESLint standards
yarn check-lint ||
(
  echo "😡🧶👋😡 うげー! なんでこった！ 😡🧶👋😡
        ESLintチェックで引っかかったぜ. この上のやつ確認して, もっかいコミットやで.";
  false;
)

# If everything passes... try to run build
echo "🤔🤔🤔🤔... いい感じかも... 今ビルド中よ... 🤔🤔🤔🤔"

# Check ESLint standards
yarn check-lint ||
(
  echo "❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
        Next build faild: View the errors above to see why.";
  false;
)

# If it builds we can commit
echo "✅ ✅ ✅  やったね! コミット完了 ✅ ✅ ✅ "