#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Styling, testing and building your project before committing"

# Check Prettier standards
yarn check-types ||
(
  echo "🤡😂❌🤡 Failed type check. 🤡😂❌🤡
        Are you seriously trying to write that? Make the changes required above.";
  false;
)

# Check Prettier standards
yarn check-format ||
(
  echo "🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
        Prettier check Faild. Run yarn format, add changes and try commit again.";
  false;
)

# Check ESLint standards
yarn check-lint ||
(
  echo "😡🧶👋😡 Get that weaks s**t out of here! 😡🧶👋😡
        ESLint check Faild. Make the required changes listed above, add changes and try to commit again.";
  false;
)

# If everything passes... try to run build
echo "🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔"

# Check ESLint standards
yarn check-lint ||
(
  echo "❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
        Next build faild: View the errors above to see why.";
  false;
)

# If it builds we can commit
echo "✅ ✅ ✅  You win this time... I am committing this now. ✅ ✅ ✅ "